// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               unknown
// source: mmp-io.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "mmpio";

export interface Variant {
  chromosome: number;
  position: number;
  ref: string;
  alt: string;
}

export interface AssociationStatistic {
  pValue: number;
  beta: number;
  sebeta: number;
  af: number;
}

export interface SummaryRecord {
  variant: Variant | undefined;
  associationStatistic: AssociationStatistic | undefined;
}

function createBaseVariant(): Variant {
  return { chromosome: 0, position: 0, ref: "", alt: "" };
}

export const Variant: MessageFns<Variant> = {
  encode(message: Variant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chromosome !== 0) {
      writer.uint32(8).uint32(message.chromosome);
    }
    if (message.position !== 0) {
      writer.uint32(16).uint64(message.position);
    }
    if (message.ref !== "") {
      writer.uint32(26).string(message.ref);
    }
    if (message.alt !== "") {
      writer.uint32(34).string(message.alt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Variant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.chromosome = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ref = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.alt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Variant {
    return {
      chromosome: isSet(object.chromosome) ? globalThis.Number(object.chromosome) : 0,
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      ref: isSet(object.ref) ? globalThis.String(object.ref) : "",
      alt: isSet(object.alt) ? globalThis.String(object.alt) : "",
    };
  },

  toJSON(message: Variant): unknown {
    const obj: any = {};
    if (message.chromosome !== 0) {
      obj.chromosome = Math.round(message.chromosome);
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.ref !== "") {
      obj.ref = message.ref;
    }
    if (message.alt !== "") {
      obj.alt = message.alt;
    }
    return obj;
  },
};

function createBaseAssociationStatistic(): AssociationStatistic {
  return { pValue: 0, beta: 0, sebeta: 0, af: 0 };
}

export const AssociationStatistic: MessageFns<AssociationStatistic> = {
  encode(message: AssociationStatistic, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pValue !== 0) {
      writer.uint32(13).float(message.pValue);
    }
    if (message.beta !== 0) {
      writer.uint32(21).float(message.beta);
    }
    if (message.sebeta !== 0) {
      writer.uint32(29).float(message.sebeta);
    }
    if (message.af !== 0) {
      writer.uint32(37).float(message.af);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssociationStatistic {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssociationStatistic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.pValue = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.beta = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.sebeta = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.af = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssociationStatistic {
    return {
      pValue: isSet(object.pValue) ? globalThis.Number(object.pValue) : 0,
      beta: isSet(object.beta) ? globalThis.Number(object.beta) : 0,
      sebeta: isSet(object.sebeta) ? globalThis.Number(object.sebeta) : 0,
      af: isSet(object.af) ? globalThis.Number(object.af) : 0,
    };
  },

  toJSON(message: AssociationStatistic): unknown {
    const obj: any = {};
    if (message.pValue !== 0) {
      obj.pValue = message.pValue;
    }
    if (message.beta !== 0) {
      obj.beta = message.beta;
    }
    if (message.sebeta !== 0) {
      obj.sebeta = message.sebeta;
    }
    if (message.af !== 0) {
      obj.af = message.af;
    }
    return obj;
  },
};

function createBaseSummaryRecord(): SummaryRecord {
  return { variant: undefined, associationStatistic: undefined };
}

export const SummaryRecord: MessageFns<SummaryRecord> = {
  encode(message: SummaryRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variant !== undefined) {
      Variant.encode(message.variant, writer.uint32(10).fork()).join();
    }
    if (message.associationStatistic !== undefined) {
      AssociationStatistic.encode(message.associationStatistic, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SummaryRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSummaryRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variant = Variant.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.associationStatistic = AssociationStatistic.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SummaryRecord {
    return {
      variant: isSet(object.variant) ? Variant.fromJSON(object.variant) : undefined,
      associationStatistic: isSet(object.associationStatistic)
        ? AssociationStatistic.fromJSON(object.associationStatistic)
        : undefined,
    };
  },

  toJSON(message: SummaryRecord): unknown {
    const obj: any = {};
    if (message.variant !== undefined) {
      obj.variant = Variant.toJSON(message.variant);
    }
    if (message.associationStatistic !== undefined) {
      obj.associationStatistic = AssociationStatistic.toJSON(message.associationStatistic);
    }
    return obj;
  },
};

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
}
