# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mmp-io.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'mmp-io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmmp-io.proto\x12\x05mmpio\"i\n\x07Variant\x12\x1e\n\nchromosome\x18\x01 \x01(\rR\nchromosome\x12\x1a\n\x08position\x18\x02 \x01(\x04R\x08position\x12\x10\n\x03ref\x18\x03 \x01(\tR\x03ref\x12\x10\n\x03\x61lt\x18\x04 \x01(\tR\x03\x61lt\"j\n\x14\x41ssociationStatistic\x12\x16\n\x06pValue\x18\x01 \x01(\x02R\x06pValue\x12\x12\n\x04\x62\x65ta\x18\x02 \x01(\x02R\x04\x62\x65ta\x12\x16\n\x06sebeta\x18\x03 \x01(\x02R\x06sebeta\x12\x0e\n\x02\x61\x66\x18\x04 \x01(\x02R\x02\x61\x66\"\x8a\x01\n\rSummaryRecord\x12(\n\x07variant\x18\x01 \x01(\x0b\x32\x0e.mmpio.VariantR\x07variant\x12O\n\x14\x61ssociationStatistic\x18\x02 \x01(\x0b\x32\x1b.mmpio.AssociationStatisticR\x14\x61ssociationStatisticB,Z*github.com/majorseitan/MMP_2024/mmp-io;libb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmp_io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/majorseitan/MMP_2024/mmp-io;lib'
  _globals['_VARIANT']._serialized_start=23
  _globals['_VARIANT']._serialized_end=128
  _globals['_ASSOCIATIONSTATISTIC']._serialized_start=130
  _globals['_ASSOCIATIONSTATISTIC']._serialized_end=236
  _globals['_SUMMARYRECORD']._serialized_start=239
  _globals['_SUMMARYRECORD']._serialized_end=377
# @@protoc_insertion_point(module_scope)
