# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summaryfile.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'summaryfile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11summaryfile.proto\x12\x0bsummaryfile\")\n\rSummaryHeader\x12\x18\n\x07\x63olumns\x18\x01 \x03(\tR\x07\x63olumns\"\'\n\rSummaryValues\x12\x16\n\x06values\x18\x01 \x03(\tR\x06values\"\xb2\x01\n\x0bSummaryRows\x12\x16\n\x06header\x18\x01 \x03(\tR\x06header\x12\x36\n\x04rows\x18\x02 \x03(\x0b\x32\".summaryfile.SummaryRows.RowsEntryR\x04rows\x1aS\n\tRowsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32\x1a.summaryfile.SummaryValuesR\x05value:\x02\x38\x01\";\n\x0bSummaryFile\x12,\n\x04rows\x18\x01 \x03(\x0b\x32\x18.summaryfile.SummaryRowsR\x04rowsB,Z*github.com/majorseitan/MMP_2024/mmp-io;libb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summaryfile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/majorseitan/MMP_2024/mmp-io;lib'
  _globals['_SUMMARYROWS_ROWSENTRY']._loaded_options = None
  _globals['_SUMMARYROWS_ROWSENTRY']._serialized_options = b'8\001'
  _globals['_SUMMARYHEADER']._serialized_start=34
  _globals['_SUMMARYHEADER']._serialized_end=75
  _globals['_SUMMARYVALUES']._serialized_start=77
  _globals['_SUMMARYVALUES']._serialized_end=116
  _globals['_SUMMARYROWS']._serialized_start=119
  _globals['_SUMMARYROWS']._serialized_end=297
  _globals['_SUMMARYROWS_ROWSENTRY']._serialized_start=214
  _globals['_SUMMARYROWS_ROWSENTRY']._serialized_end=297
  _globals['_SUMMARYFILE']._serialized_start=299
  _globals['_SUMMARYFILE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
