// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mmp-io.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chromosome    uint32                 `protobuf:"varint,1,opt,name=chromosome,proto3" json:"chromosome,omitempty"`
	Position      uint64                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Alt           string                 `protobuf:"bytes,4,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_mmp_io_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_mmp_io_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_mmp_io_proto_rawDescGZIP(), []int{0}
}

func (x *Variant) GetChromosome() uint32 {
	if x != nil {
		return x.Chromosome
	}
	return 0
}

func (x *Variant) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Variant) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Variant) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

type AssociationStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PValue        float32                `protobuf:"fixed32,1,opt,name=pValue,proto3" json:"pValue,omitempty"`
	Beta          float32                `protobuf:"fixed32,2,opt,name=beta,proto3" json:"beta,omitempty"`
	Sebeta        float32                `protobuf:"fixed32,3,opt,name=sebeta,proto3" json:"sebeta,omitempty"`
	Af            float32                `protobuf:"fixed32,4,opt,name=af,proto3" json:"af,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociationStatistic) Reset() {
	*x = AssociationStatistic{}
	mi := &file_mmp_io_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociationStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociationStatistic) ProtoMessage() {}

func (x *AssociationStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_mmp_io_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociationStatistic.ProtoReflect.Descriptor instead.
func (*AssociationStatistic) Descriptor() ([]byte, []int) {
	return file_mmp_io_proto_rawDescGZIP(), []int{1}
}

func (x *AssociationStatistic) GetPValue() float32 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *AssociationStatistic) GetBeta() float32 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *AssociationStatistic) GetSebeta() float32 {
	if x != nil {
		return x.Sebeta
	}
	return 0
}

func (x *AssociationStatistic) GetAf() float32 {
	if x != nil {
		return x.Af
	}
	return 0
}

type SummaryRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Variant              *Variant               `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	AssociationStatistic *AssociationStatistic  `protobuf:"bytes,2,opt,name=associationStatistic,proto3" json:"associationStatistic,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SummaryRecord) Reset() {
	*x = SummaryRecord{}
	mi := &file_mmp_io_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRecord) ProtoMessage() {}

func (x *SummaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mmp_io_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRecord.ProtoReflect.Descriptor instead.
func (*SummaryRecord) Descriptor() ([]byte, []int) {
	return file_mmp_io_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryRecord) GetVariant() *Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *SummaryRecord) GetAssociationStatistic() *AssociationStatistic {
	if x != nil {
		return x.AssociationStatistic
	}
	return nil
}

var File_mmp_io_proto protoreflect.FileDescriptor

const file_mmp_io_proto_rawDesc = "" +
	"\n" +
	"\fmmp-io.proto\x12\x05mmpio\"i\n" +
	"\aVariant\x12\x1e\n" +
	"\n" +
	"chromosome\x18\x01 \x01(\rR\n" +
	"chromosome\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x04R\bposition\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\tR\x03alt\"j\n" +
	"\x14AssociationStatistic\x12\x16\n" +
	"\x06pValue\x18\x01 \x01(\x02R\x06pValue\x12\x12\n" +
	"\x04beta\x18\x02 \x01(\x02R\x04beta\x12\x16\n" +
	"\x06sebeta\x18\x03 \x01(\x02R\x06sebeta\x12\x0e\n" +
	"\x02af\x18\x04 \x01(\x02R\x02af\"\x8a\x01\n" +
	"\rSummaryRecord\x12(\n" +
	"\avariant\x18\x01 \x01(\v2\x0e.mmpio.VariantR\avariant\x12O\n" +
	"\x14associationStatistic\x18\x02 \x01(\v2\x1b.mmpio.AssociationStatisticR\x14associationStatisticB,Z*github.com/majorseitan/MMP_2024/mmp-io;libb\x06proto3"

var (
	file_mmp_io_proto_rawDescOnce sync.Once
	file_mmp_io_proto_rawDescData []byte
)

func file_mmp_io_proto_rawDescGZIP() []byte {
	file_mmp_io_proto_rawDescOnce.Do(func() {
		file_mmp_io_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmp_io_proto_rawDesc), len(file_mmp_io_proto_rawDesc)))
	})
	return file_mmp_io_proto_rawDescData
}

var file_mmp_io_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mmp_io_proto_goTypes = []any{
	(*Variant)(nil),              // 0: mmpio.Variant
	(*AssociationStatistic)(nil), // 1: mmpio.AssociationStatistic
	(*SummaryRecord)(nil),        // 2: mmpio.SummaryRecord
}
var file_mmp_io_proto_depIdxs = []int32{
	0, // 0: mmpio.SummaryRecord.variant:type_name -> mmpio.Variant
	1, // 1: mmpio.SummaryRecord.associationStatistic:type_name -> mmpio.AssociationStatistic
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mmp_io_proto_init() }
func file_mmp_io_proto_init() {
	if File_mmp_io_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmp_io_proto_rawDesc), len(file_mmp_io_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mmp_io_proto_goTypes,
		DependencyIndexes: file_mmp_io_proto_depIdxs,
		MessageInfos:      file_mmp_io_proto_msgTypes,
	}.Build()
	File_mmp_io_proto = out.File
	file_mmp_io_proto_goTypes = nil
	file_mmp_io_proto_depIdxs = nil
}
