// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: summaryfile.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SummaryHeader contains the column names for the summary data
type SummaryHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryHeader) Reset() {
	*x = SummaryHeader{}
	mi := &file_summaryfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryHeader) ProtoMessage() {}

func (x *SummaryHeader) ProtoReflect() protoreflect.Message {
	mi := &file_summaryfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryHeader.ProtoReflect.Descriptor instead.
func (*SummaryHeader) Descriptor() ([]byte, []int) {
	return file_summaryfile_proto_rawDescGZIP(), []int{0}
}

func (x *SummaryHeader) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// SummaryValues contains the values for a single variant row
type SummaryValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryValues) Reset() {
	*x = SummaryValues{}
	mi := &file_summaryfile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryValues) ProtoMessage() {}

func (x *SummaryValues) ProtoReflect() protoreflect.Message {
	mi := &file_summaryfile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryValues.ProtoReflect.Descriptor instead.
func (*SummaryValues) Descriptor() ([]byte, []int) {
	return file_summaryfile_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// SummaryRows contains a map of variant (VariantKey) to values
type SummaryRows struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Header        []string                  `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	Rows          map[string]*SummaryValues `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is VariantKey: "chrom\tpos\tref\talt"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRows) Reset() {
	*x = SummaryRows{}
	mi := &file_summaryfile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRows) ProtoMessage() {}

func (x *SummaryRows) ProtoReflect() protoreflect.Message {
	mi := &file_summaryfile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRows.ProtoReflect.Descriptor instead.
func (*SummaryRows) Descriptor() ([]byte, []int) {
	return file_summaryfile_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryRows) GetHeader() []string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SummaryRows) GetRows() map[string]*SummaryValues {
	if x != nil {
		return x.Rows
	}
	return nil
}

// SummaryFile represents the complete summary file structure
type SummaryFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*SummaryRows         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryFile) Reset() {
	*x = SummaryFile{}
	mi := &file_summaryfile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryFile) ProtoMessage() {}

func (x *SummaryFile) ProtoReflect() protoreflect.Message {
	mi := &file_summaryfile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryFile.ProtoReflect.Descriptor instead.
func (*SummaryFile) Descriptor() ([]byte, []int) {
	return file_summaryfile_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryFile) GetRows() []*SummaryRows {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_summaryfile_proto protoreflect.FileDescriptor

const file_summaryfile_proto_rawDesc = "" +
	"\n" +
	"\x11summaryfile.proto\x12\vsummaryfile\")\n" +
	"\rSummaryHeader\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"'\n" +
	"\rSummaryValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xb2\x01\n" +
	"\vSummaryRows\x12\x16\n" +
	"\x06header\x18\x01 \x03(\tR\x06header\x126\n" +
	"\x04rows\x18\x02 \x03(\v2\".summaryfile.SummaryRows.RowsEntryR\x04rows\x1aS\n" +
	"\tRowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.summaryfile.SummaryValuesR\x05value:\x028\x01\";\n" +
	"\vSummaryFile\x12,\n" +
	"\x04rows\x18\x01 \x03(\v2\x18.summaryfile.SummaryRowsR\x04rowsB,Z*github.com/majorseitan/MMP_2024/mmp-io;libb\x06proto3"

var (
	file_summaryfile_proto_rawDescOnce sync.Once
	file_summaryfile_proto_rawDescData []byte
)

func file_summaryfile_proto_rawDescGZIP() []byte {
	file_summaryfile_proto_rawDescOnce.Do(func() {
		file_summaryfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_summaryfile_proto_rawDesc), len(file_summaryfile_proto_rawDesc)))
	})
	return file_summaryfile_proto_rawDescData
}

var file_summaryfile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_summaryfile_proto_goTypes = []any{
	(*SummaryHeader)(nil), // 0: summaryfile.SummaryHeader
	(*SummaryValues)(nil), // 1: summaryfile.SummaryValues
	(*SummaryRows)(nil),   // 2: summaryfile.SummaryRows
	(*SummaryFile)(nil),   // 3: summaryfile.SummaryFile
	nil,                   // 4: summaryfile.SummaryRows.RowsEntry
}
var file_summaryfile_proto_depIdxs = []int32{
	4, // 0: summaryfile.SummaryRows.rows:type_name -> summaryfile.SummaryRows.RowsEntry
	2, // 1: summaryfile.SummaryFile.rows:type_name -> summaryfile.SummaryRows
	1, // 2: summaryfile.SummaryRows.RowsEntry.value:type_name -> summaryfile.SummaryValues
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_summaryfile_proto_init() }
func file_summaryfile_proto_init() {
	if File_summaryfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_summaryfile_proto_rawDesc), len(file_summaryfile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_summaryfile_proto_goTypes,
		DependencyIndexes: file_summaryfile_proto_depIdxs,
		MessageInfos:      file_summaryfile_proto_msgTypes,
	}.Build()
	File_summaryfile_proto = out.File
	file_summaryfile_proto_goTypes = nil
	file_summaryfile_proto_depIdxs = nil
}
